import {db} from './db';
type Row=Record<string,unknown>;
/** An explicit projection: no supplier costs, internal notes or private audit payloads. */
export function recentFinancialActivity(clientId:number,includeActor=false){
 const ledger=db.prepare(`SELECT e.id,e.created_at,e.occurred_at,e.entry_type,e.direction,e.amount,e.reference_type,e.reference_id,u.display_name actor,
 EXISTS(SELECT 1 FROM rejected_payments p WHERE p.ledger_id=e.id) reversed
 FROM ledger_entries e LEFT JOIN users u ON u.id=e.created_by_user_id WHERE e.client_user_id=? AND e.entry_type NOT IN ('SERVICE_COST') ORDER BY e.created_at DESC,e.id DESC LIMIT 50`).all(clientId) as Row[];
 const moves=ledger.map(e=>{const allocations=db.prepare('SELECT statement_id,debt_id,amount_cents FROM credit_allocations WHERE ledger_id=?').all(e.id) as Row[];
 const applied=allocations.reduce((n,a)=>n+Number(a.amount_cents),0),credit=e.direction==='CREDIT';
 return {id:'ledger-'+e.id,ledger_id:e.id,recorded_at:e.created_at,occurred_at:e.occurred_at,type:e.entry_type,reference:String(e.reference_type||'Ledger')+' #'+String(e.reference_id||e.id),amount_cents:Math.round(Number(e.amount)*100)*(credit?1:-1),destination:e.reversed?'Reversed':credit?(allocations.map(a=>(a.debt_id?'Debt #'+a.debt_id:'Statement #'+a.statement_id)+' $'+(Number(a.amount_cents)/100).toFixed(2)).join(', ')+(applied<Math.round(Number(e.amount)*100)?(applied?' + Wallet':'Wallet')+' $'+((Math.round(Number(e.amount)*100)-applied)/100).toFixed(2):'')||'Wallet'):e.entry_type==='PAYMENT_REVERSAL'?'Wallet / restored AR':'Charges / Usage',status:e.reversed||e.entry_type==='PAYMENT_REVERSAL'?'Reversed':credit&&applied>0&&applied<Math.round(Number(e.amount)*100)?'Partially Applied':credit&&applied>0?'Applied':credit?'Credited to Wallet':'Completed',...(includeActor?{actor:e.actor||'System'}:{})};});
 const applications=(db.prepare(`SELECT a.id,a.created_at,a.data_json,u.display_name actor FROM financial_audit a LEFT JOIN users u ON u.id=a.actor_id WHERE a.client_id=? AND a.event IN ('apply_credit','allocate') ORDER BY a.id DESC LIMIT 50`).all(clientId) as Row[]).map(a=>{const payload=JSON.parse(String(a.data_json)),allocations=(payload.allocations||[]) as Row[];const applied=allocations.reduce((n,t)=>n+Math.round(Number(t.amount)*100),0);return {id:'allocation-'+a.id,recorded_at:a.created_at,occurred_at:a.created_at,type:payload.action==='allocate'?'ALLOCATE_PAYMENT':'APPLY_CREDIT',reference:'Ledger #'+payload.ledger_id,amount_cents:payload.allocation_delta_cents===undefined?-applied:-Number(payload.allocation_delta_cents),...(payload.allocation_delta_cents===undefined?{amount_label:'Phân bổ $'+(applied/100).toFixed(2)}:{}),destination:allocations.map(t=>t.debt_id?'Debt #'+t.debt_id:'Statement #'+t.statement_id).join(', ')||'Wallet',status:'Completed',...(includeActor?{actor:a.actor||'System'}:{})};});
 return [...moves,...applications].sort((a,b)=>String(b.recorded_at).localeCompare(String(a.recorded_at))).slice(0,50);
}
