"use client";
import {useCallback,useEffect,useState} from 'react';
type Row=Record<string,unknown>;
const usd=(n:unknown)=>'$'+(Number(n||0)/100).toFixed(2);
export function FinancialWorkspace({role,clients}:{role:string;clients:Row[]}){
 const [client,setClient]=useState(''),[data,setData]=useState<Row|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[tab,setTab]=useState('statements'),[selected,setSelected]=useState<{kind:string;row:Row}|null>(null);
 const load=useCallback(async()=>{if(role!=='CLIENT'&&!client){setData(null);return}setLoading(true);try{const r=await fetch('/api/financials?client_id='+client);const d=await r.json();if(!r.ok)throw Error(d.error);setData(d);setError('')}catch(e){setError((e as Error).message)}finally{setLoading(false)}},[role,client]);
 useEffect(()=>{void load()},[load]);
 const rows=(key:string)=>(data?.[key]||[]) as Row[];
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);try{const b:Row=Object.fromEntries(new FormData(e.currentTarget));if(b.action==='allocate'||b.action==='apply_credit'){const [kind,id]=String(b.target).split(':');b.allocations=kind==='balance'?[]:[{[kind==='debt'?'debt_id':'statement_id']:Number(id),amount:Number(b.amount)}]}const r=await fetch('/api/financials',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...b,client_id:client,purchase_locked:b.purchase_locked==='on',exclude_room:b.exclude_room==='on'})});const d=await r.json();if(!r.ok)throw Error(d.error);setData(d);setError('');setSelected(null)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function dispute(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);try{const b=Object.fromEntries(new FormData(e.currentTarget));const r=await fetch('/api/cases',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...b,action:'create',kind:'CLAIM',visibility:'PUBLIC',statement_id:selected?.row.id,order_ids:selected?.row.order_ids})});const d=await r.json();if(!r.ok)throw Error(d.error);setError('');setSelected(null);setNotice('Đã mở Claim #'+d.id+' cho Statement. Theo dõi tại Cases / Claims.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const button=<button className="primaryBtn" disabled={busy}>{busy?'Đang lưu…':'Lưu'}</button>;
 return <section className="panel financialWorkspace"><h2>Tài chính Client</h2>{role!=='CLIENT'&&<label className="field">Client<select aria-label="Client tài chính" value={client} onChange={e=>{setData(null);setSelected(null);setClient(e.target.value)}}><option value="">Chọn Client</option>{clients.map(c=><option key={String(c.id)} value={String(c.id)}>{String(c.display_name)}</option>)}</select></label>}{error&&<p role="alert">{error} <button onClick={()=>void load()}>Thử lại</button></p>}{notice&&<p role="status">{notice}</p>}{loading&&<p role="status">Đang tải tài chính…</p>}{!data&&!loading&&<p className="emptyState">Chọn Client để xem balance và công nợ.</p>}{data&&<><div className="metricGrid">{[['Wallet / Purchasing Balance',data.purchasing_balance_cents,'transactions'],['Accounts Receivable',data.receivable_cents,'statements'],['Đang giữ cho đơn mua',data.reserved_cents,'statements'],['Có thể mua (gồm credit)',data.available_to_buy_cents,'controls']].map(([name,n,key])=><button className="metricCard" key={String(name)} onClick={()=>setTab(String(key))}><span>{String(name)}</span><b>{usd(n)}</b></button>)}</div><p>Wallet là credit chưa cấn công nợ. Refund / Compensation mặc định vào balance; Payment / Offset tự cấn khoản nợ cũ nhất. Room mua xét balance ròng {usd(data.balance_cents)}, credit limit, khoản giữ và các lý do chặn.</p>{(data.reasons as string[]).length>0&&<p role="status">Mua đơn đang bị chặn: {(data.reasons as string[]).join('; ')}</p>}{role==='ADMIN'&&rows('legacy_allocations').length>0&&<p role="status">Có {rows('legacy_allocations').length} allocation credit lịch sử cần đối soát. Dữ liệu cũ được giữ nguyên; chọn từng giao dịch để quyết định phân bổ.</p>}<nav className="opsTabs">{[['statements','Statements'],['debts','Debt Items'],['transactions','Payments / Credits'],['fees','Fees'],...(role!=='CLIENT'?[['controls','Điều khiển Client']]:[])].map(([key,label])=><button key={key} className={tab===key?'primaryBtn':'secondaryBtn'} onClick={()=>setTab(key)}>{label}</button>)}</nav>
 {['statements','debts'].includes(tab)&&<><p>{tab==='statements'?'Kỳ Thứ 2–Chủ nhật. ISSUED được khóa; sai dữ liệu xử lý qua Claim. Trạng thái thanh toán được tính riêng.':'Debt giữ reference kỳ gốc; FIFO xét thời điểm khoản nợ gốc.'}</p>{rows(tab).length?<div className="tableWrap"><table><thead><tr><th>Kỳ / lý do</th><th>Lifecycle</th><th>Deadline</th><th>Tổng</th><th>Còn lại</th><th>Thanh toán</th><th>Chi tiết</th></tr></thead><tbody>{rows(tab).map(r=><tr key={String(r.id)}><td>#{String(r.id)} · {String(r.period_start||r.reason)} {r.period_end?' → '+r.period_end:''}</td><td><span className="status">{String(r.lifecycle||r.source_type)}</span></td><td>{String(r.deadline)}</td><td>{usd(r.original_total_cents??r.amount_cents)}</td><td>{usd(r.outstanding_cents)}</td><td>{String(r.status)}</td><td><button className="rowAction" onClick={()=>setSelected({kind:tab,row:r})}>Chi tiết</button></td></tr>)}</tbody></table></div>:<p className="emptyState">Chưa có khoản trong mục này.</p>}</>}
 {['transactions','fees'].includes(tab)&&<div className="tableWrap"><table><thead><tr><th>Giao dịch</th><th>Ngày</th><th>Số tiền</th><th>Đã cấn AR</th><th>Nội dung</th><th>Thao tác</th></tr></thead><tbody>{rows('transactions').filter(r=>tab==='fees'?r.entry_type==='ADDITIONAL_FEE':r.direction==='CREDIT').map(r=><tr key={String(r.id)}><td>#{String(r.id)} · {String(r.entry_type)}{r.rejected?' · REJECTED':''}</td><td>{String(r.occurred_at||r.created_at)}</td><td>{usd(Number(r.amount)*100)}</td><td>{usd(r.allocated_cents)}</td><td>{String(r.note||'')}</td><td>{role==='ADMIN'&&r.direction==='CREDIT'&&!r.rejected&&<button className="rowAction" onClick={()=>setSelected({kind:'credit',row:r})}>{['PAYMENT','OFFSET','SERVICE_SETTLEMENT'].includes(String(r.entry_type))?'Phân bổ / để lại Balance':'Apply Credit to Receivables'}</button>}</td></tr>)}</tbody></table></div>}
 {tab==='controls'&&role!=='CLIENT'&&<>{role==='ADMIN'&&<form className="opsForm settingsGrid" onSubmit={submit}><h3>Credit & khóa mua · {clients.find(c=>String(c.id)===client)?.display_name as string}</h3><input type="hidden" name="action" value="configure"/><label className="field">Credit limit USD<input name="credit_limit" type="number" min="0" step="0.01" defaultValue={Number(data.credit_limit_cents)/100} key={client+'limit'} required/></label><label className="field">Credit term ngày<input name="credit_term_days" type="number" min="1" max="365" defaultValue={Number(data.credit_term_days)} key={client+'term'} required/></label><label><input type="checkbox" name="purchase_locked" defaultChecked={Boolean(data.purchase_locked)} key={client+String(data.purchase_locked)}/>Khóa mua thủ công</label><label className="field">Lý do<input name="reason" defaultValue={String(data.purchase_lock_reason||'')}/></label>{button}</form>}<form className="opsForm settingsGrid" onSubmit={submit}><h3>Phí bổ sung cho Client đang chọn</h3><input type="hidden" name="action" value="additional_fee"/><label className="field">Ngày<input name="occurred_at" type="date" required/></label><label className="field">Số lượng<input name="quantity" type="number" min="1" defaultValue="1" required/></label><label className="field">Đơn giá USD<input name="unit_price" type="number" min="0.01" step="0.01" required/></label><label className="field">Nội dung<input name="note" required/></label>{button}</form></>}
 </>}
 {selected&&<div className="modalBackdrop"><section className="modalPanel" role="dialog" aria-modal="true" aria-label="Chi tiết tài chính"><header className="modalHeader"><h2>#{String(selected.row.id)} · {selected.kind==='credit'?String(selected.row.entry_type):selected.kind}</h2><button className="iconBtn" aria-label="Đóng tài chính" onClick={()=>setSelected(null)}>×</button></header><div className="modalBody">{error&&<p role="alert">{error}</p>}
 {selected.kind==='statements'&&<><p>{String(selected.row.lifecycle)} · {String(selected.row.status)} · Deadline {String(selected.row.deadline)}</p><div className="tableWrap"><table><thead><tr><th>Ledger</th><th>Loại</th><th>Số tiền</th><th>Reference kỳ gốc / ngày / lý do</th></tr></thead><tbody>{rows('items').filter(i=>i.statement_id===selected.row.id).map(i=><tr key={String(i.direction)+String(i.id)}><td>{String(i.ledger_id)}</td><td>{String(i.item_type)} · {String(i.direction)}</td><td>{usd(i.amount_cents)}</td><td>{i.original_occurred_at?(i.original_statement_id?'Statement #'+i.original_statement_id+' · ':'')+i.original_occurred_at+' · '+i.adjustment_reason:'—'}</td></tr>)}</tbody></table></div>{Array.isArray(selected.row.order_ids)&&selected.row.order_ids.length>0&&<form className="opsForm settingsGrid" onSubmit={dispute}><h3>Tranh chấp Statement qua Claim</h3><label className="field">Mô tả sai sót<input name="summary" required maxLength={2000}/></label><button className="primaryBtn" disabled={busy}>Mở Claim cho kỳ này</button></form>}{role==='ADMIN'&&Number(selected.row.outstanding_cents)>0&&<form className="opsForm settingsGrid" onSubmit={submit}><h3>Tách Debt từ Statement đang chọn</h3><input type="hidden" name="action" value="debt"/><input type="hidden" name="statement_id" value={String(selected.row.id)}/><label className="field">Số tiền USD<input name="amount" type="number" min="0.01" max={Number(selected.row.outstanding_cents)/100} step="0.01" required/></label><label className="field">Deadline<input name="deadline" type="date" required/></label><label className="field">Lý do<input name="reason" required/></label><label><input type="checkbox" name="exclude_room"/>Tách khỏi room mua</label>{button}</form>}</>}
 {selected.kind==='debts'&&<><p>{String(selected.row.reason)} · Kỳ gốc #{String(selected.row.source_statement_id)} · Còn lại {usd(selected.row.outstanding_cents)}</p>{role==='ADMIN'&&<form className="opsForm settingsGrid" onSubmit={submit}><input type="hidden" name="action" value="extend_debt"/><input type="hidden" name="debt_id" value={String(selected.row.id)}/><label className="field">Deadline mới<input name="deadline" type="date" required/></label>{button}</form>}</>}
 {selected.kind==='credit'&&role==='ADMIN'&&<><p>Tổng {usd(Number(selected.row.amount)*100)} · Đã cấn {usd(selected.row.allocated_cents)}. Phân bổ thay thế chỉ dùng tiền của giao dịch này; phần dư giữ tại Purchasing Balance.</p><form className="opsForm settingsGrid" onSubmit={submit}><input type="hidden" name="action" value={['PAYMENT','OFFSET','SERVICE_SETTLEMENT'].includes(String(selected.row.entry_type))?'allocate':'apply_credit'}/><input type="hidden" name="ledger_id" value={String(selected.row.id)}/><label className="field">Khoản đích<select name="target"><option value="balance">Giữ toàn bộ tại Purchasing Balance</option>{['debts','statements'].flatMap(kind=>rows(kind).filter(r=>Number(r.outstanding_cents)>0||rows('allocations').some(a=>a.ledger_id===selected.row.id&&a[kind==='debts'?'debt_id':'statement_id']===r.id)).map(r=><option key={kind+String(r.id)} value={(kind==='debts'?'debt:':'statement:')+r.id}>{kind==='debts'?'Debt':'Statement'} #{String(r.id)} · {String(r.reason||r.period_start)} · {usd(r.outstanding_cents)}</option>))}</select></label><label className="field">Số tiền USD (nếu cấn AR)<input name="amount" type="number" min="0.01" max={Number(selected.row.amount)} step="0.01"/></label><label className="field">Lý do audit<input name="reason" required/></label>{button}</form>{selected.row.entry_type==='PAYMENT'&&<form className="opsForm settingsGrid" onSubmit={submit}><h3>Reject Payment</h3><input type="hidden" name="action" value="reject_payment"/><input type="hidden" name="ledger_id" value={String(selected.row.id)}/><label className="field">Lý do<input name="reason" required/></label>{button}</form>}</>}
 </div></section></div>}
 </section>;
}
