"use client";
import {useCallback,useEffect,useState} from "react";
type Row=Record<string,unknown>;
const usd=(n:unknown)=>"$"+(Number(n||0)/100).toFixed(2);
export function FinancialWorkspace({role,clients}:{role:string;clients:Row[]}){
 const [client,setClient]=useState(""),[data,setData]=useState<Row|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{if(role!=="CLIENT"&&!client)return;const r=await fetch("/api/financials?client_id="+client);const d=await r.json();if(r.ok){setData(d);setError("");}else setError(d.error);},[role,client]);
 useEffect(()=>{void load()},[load]);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);try{const b:Record<string,unknown>=Object.fromEntries(new FormData(e.currentTarget));if(b.action==="allocate")b.allocations=[{[b.target_kind==="debt"?"debt_id":"statement_id"]:Number(b.target_id),amount:Number(b.amount)}];const r=await fetch("/api/financials",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...b,client_id:client,purchase_locked:b.purchase_locked==="on",exclude_room:b.exclude_room==="on"})});const d=await r.json();if(!r.ok)throw Error(d.error);setData(d);setError("");}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const rows=(key:string)=>(data?.[key]||[]) as Row[];
 return <section className="panel"><h2>Đối soát & công nợ</h2>{role!=="CLIENT"&&<label>Client <select aria-label="Client tài chính" value={client} onChange={e=>setClient(e.target.value)}><option value="">Chọn Client</option>{clients.map(c=><option key={String(c.id)} value={String(c.id)}>{String(c.display_name)}</option>)}</select></label>}{error&&<p role="alert">{error}</p>}{data&&<>
 <div className="metricGrid">{[["Balance",data.balance_cents],["Đang giữ",data.reserved_cents],["Credit đã dùng",data.credit_used_cents],["Có thể mua",data.available_to_buy_cents]].map(([name,n])=><div className="metricCard" key={String(name)}><span>{String(name)}</span><b>{usd(n)}</b></div>)}</div>
 {Boolean(data.purchase_blocked)&&<p role="status">Mua đơn đang bị chặn: {(data.reasons as string[]).join("; ")}</p>}
 {["statements","debts"].map(key=><div key={key}><h3>{key==="debts"?"Khoản công nợ riêng":"Kỳ đối soát Thứ 2 – Chủ nhật"}</h3><div className="tableWrap"><table><thead><tr><th>ID</th><th>Kỳ / lý do</th><th>Deadline</th><th>Số tiền</th><th>Còn lại</th><th>Trạng thái</th></tr></thead><tbody>{rows(key).map(r=><tr key={String(r.id)}><td>{String(r.id)}</td><td>{String(r.period_start||r.reason||"")}{r.period_end?" → "+String(r.period_end):""}</td><td>{String(r.deadline)}</td><td>{usd(r.amount_cents)}</td><td>{usd(r.outstanding_cents)}</td><td>{String(r.status)}</td></tr>)}</tbody></table></div></div>)}
 <details><summary>Phân bổ thanh toán</summary><div className="tableWrap"><table><thead><tr><th>Ledger ID</th><th>Statement</th><th>Debt</th><th>Số tiền</th></tr></thead><tbody>{rows("allocations").map(r=><tr key={String(r.id)}><td>{String(r.ledger_id)}</td><td>{String(r.statement_id||"")}</td><td>{String(r.debt_id||"")}</td><td>{usd(r.amount_cents)}</td></tr>)}</tbody></table></div></details>
 {role==="ADMIN"&&<><form onSubmit={submit}><h3>Credit & khóa mua</h3><input type="hidden" name="action" value="configure"/><label>Credit limit USD <input name="credit_limit" type="number" min="0" step="0.01" defaultValue={Number(data.credit_limit_cents)/100} key={client+"limit"} required/></label><label>Credit term ngày <input name="credit_term_days" type="number" min="1" max="365" defaultValue={Number(data.credit_term_days)} key={client+"term"} required/></label><label><input type="checkbox" name="purchase_locked" defaultChecked={Boolean(data.purchase_locked)} key={client+String(data.purchase_locked)}/>Khóa mua</label><input name="reason" aria-label="Lý do khóa mua" placeholder="Lý do"/><button disabled={busy}>Lưu</button></form>
 <form onSubmit={submit}><h3>Override phân bổ Payment</h3><input type="hidden" name="action" value="allocate"/><input name="ledger_id" aria-label="Payment ID override" placeholder="Payment Ledger ID" required/><select name="target_kind" aria-label="Loại khoản nợ"><option value="statement">Statement</option><option value="debt">Debt</option></select><input name="target_id" aria-label="Khoản nợ ID" placeholder="Statement / Debt ID" required/><input name="amount" type="number" min="0.01" step="0.01" aria-label="Số tiền phân bổ" required/><button disabled={busy}>Phân bổ</button></form>
 <form onSubmit={submit}><h3>Tách khoản nợ riêng</h3><input type="hidden" name="action" value="debt"/><input name="statement_id" aria-label="Statement ID" type="number" placeholder="Statement ID" required/><input name="amount" aria-label="Số tiền nợ USD" type="number" min="0.01" step="0.01" placeholder="USD" required/><input name="deadline" aria-label="Deadline khoản nợ" type="date" required/><input name="reason" placeholder="Lý do" required/><label><input type="checkbox" name="exclude_room"/>Tách khỏi room mua</label><button disabled={busy}>Tạo debt</button></form>
 <form onSubmit={submit}><input type="hidden" name="action" value="extend_debt"/><input name="debt_id" aria-label="Debt ID" placeholder="Debt ID" required/><input name="deadline" type="date" aria-label="Deadline mới" required/><button disabled={busy}>Gia hạn debt</button></form>
 <form onSubmit={submit}><input type="hidden" name="action" value="reject_payment"/><input name="ledger_id" aria-label="Payment Ledger ID" placeholder="Payment Ledger ID" required/><input name="reason" placeholder="Lý do reject" required/><button disabled={busy}>Reject payment</button></form></>}
 {role!=="CLIENT"&&<form onSubmit={submit}><h3>Phí bổ sung</h3><input type="hidden" name="action" value="additional_fee"/><input name="occurred_at" type="date" aria-label="Ngày phí" required/><input name="quantity" type="number" min="1" defaultValue="1" aria-label="Số lượng" required/><input name="unit_price" type="number" min="0.01" step="0.01" placeholder="Đơn giá USD" aria-label="Đơn giá USD" required/><input name="note" placeholder="Nội dung phí" required/><button disabled={busy}>Thu phí</button></form>}
 </>}</section>;
}
