"use client";

import {FormEvent,useCallback,useEffect,useRef,useState} from "react";

type ManifestCarton={id:number;carton_code:string;service:string;manifest_date:string;daily_sequence:number;sub_service:string;supplier:string;route_config_id:number;segment_key?:string;status:"OPEN"|"PAUSED"|"CLOSED";item_count:number;order_count:number;created_at:string;closed_at?:string|null;exported_at?:string|null;created_by_name?:string|null;closed_by_name?:string|null};
type ManifestItem={item_id:number;order_id:number;order_carton_id:number;tracking_id:number;tracking:string;tracking_status:string;carton_number:number;system_order_code:string;client_order_id:string;customer:string;recipient_name:string;service:string;sub_service:string;supplier:string;added_by_name?:string};
type Detail={carton:ManifestCarton;items:ManifestItem[];history?:{id:number;action:string;actor_name:string;created_at:string}[];added_count?:number};

async function responseJson(response:Response){const body=await response.json();if(!response.ok)throw new Error((body.reason_code?body.reason_code+" · ":"")+(body.error||"Không thể xử lý"));return body}
function displayDate(value:string){const match=value?.match(/^(\d{4})-(\d{2})-(\d{2})/);return match?`${match[3]}/${match[2]}/${match[1]}`:value}

export function ManifestScanPanel(){
  const input=useRef<HTMLInputElement>(null);
  const activeId=useRef<number|undefined>(undefined);
  const [cartons,setCartons]=useState<ManifestCarton[]>([]);const [active,setActive]=useState<Detail|null>(null);
  const [mode,setMode]=useState<"ADD"|"REMOVE">("ADD");
  const [value,setValue]=useState("");const [paste,setPaste]=useState("");const [busy,setBusy]=useState(false);const [notice,setNotice]=useState("");

  const load=useCallback(async(preferredId?:number)=>{
    const list=await responseJson(await fetch("/api/manifest-cartons?limit=40")) as {cartons:ManifestCarton[]};setCartons(list.cartons);
    const id=preferredId||activeId.current||list.cartons.find(row=>row.status==="OPEN")?.id||list.cartons[0]?.id;
    if(!id){activeId.current=undefined;setActive(null);return}
    const detail=await responseJson(await fetch("/api/manifest-cartons/"+id)) as Detail;activeId.current=id;setActive(detail);
  },[]);
  useEffect(()=>{void load()},[load]);

  async function addIdentifiers(raw:string){
    const identifiers=raw.split(/[\n,;]+/).map(item=>item.trim()).filter(Boolean);if(!identifiers.length)return;
    setBusy(true);setNotice("");let currentId=active?.carton.id;let added=0;const errors:string[]=[];
    try{for(const identifier of identifiers){try{const detail=await responseJson(await fetch("/api/manifest-cartons",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({identifier,manifest_carton_id:currentId,mode})})) as Detail;currentId=detail.carton.id;activeId.current=currentId;added+=Number(detail.added_count||(detail as Detail & {removed_count?:number}).removed_count||0);setActive(detail)}catch(error){errors.push(`${identifier}: ${(error as Error).message}`)}}
      setValue("");setPaste("");await load(currentId);setNotice([added?`Đã ${mode==="ADD"?"thêm":"bốc ra"} ${added} kiện.`:"",...errors.map(error=>"Lỗi · "+error)].filter(Boolean).join("\n"));
    }finally{setBusy(false);input.current?.focus()}
  }

  async function statusCarton(action:string){if(!active)return;setBusy(true);try{await responseJson(await fetch(`/api/manifest-cartons/${active.carton.id}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action})}));await load(active.carton.id);setNotice("Đã cập nhật trạng thái thùng.")}catch(error){setNotice("Lỗi · "+(error as Error).message)}finally{setBusy(false)}}
  async function removeItem(itemId:number){if(!active)return;setBusy(true);setNotice("");try{const detail=await responseJson(await fetch(`/api/manifest-cartons/${active.carton.id}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"remove",item_id:itemId})})) as Detail;setActive(detail);await load(detail.carton.id);setNotice("Đã bỏ kiện khỏi thùng.")}catch(error){setNotice("Lỗi · "+(error as Error).message)}finally{setBusy(false);input.current?.focus()}}
  async function closeCarton(){if(!active||!window.confirm(`Chốt thùng ${active.carton.carton_code}? Có thể mở lại để chỉnh.`))return;setBusy(true);setNotice("");try{const result=await responseJson(await fetch(`/api/manifest-cartons/${active.carton.id}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"close"})})) as {closed:Detail;next:Detail};activeId.current=result.next.carton.id;setActive(result.next);await load(result.next.carton.id);setNotice(`Đã đóng ${result.closed.carton.carton_code}. Đang chuyển sang ${result.next.carton.carton_code}.`)}catch(error){setNotice("Lỗi · "+(error as Error).message)}finally{setBusy(false);input.current?.focus()}}
  async function exportCarton(carton:ManifestCarton){setBusy(true);setNotice("");try{const response=await fetch("/api/manifest-export",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({manifest_carton_id:carton.id})});if(!response.ok){const body=await response.json();throw new Error(body.error)}const disposition=response.headers.get("content-disposition")||"";const filename=disposition.match(/filename="([^"]+)"/)?.[1]||carton.carton_code+".xlsx";const url=URL.createObjectURL(await response.blob());const link=document.createElement("a");link.href=url;link.download=filename;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);await load(carton.id);setNotice("Đã xuất Manifest · "+filename)}catch(error){setNotice("Lỗi · "+(error as Error).message)}finally{setBusy(false)}}
  async function chooseCarton(id:number){setBusy(true);setNotice("");try{activeId.current=id;await load(id)}catch(error){setNotice("Lỗi · "+(error as Error).message)}finally{setBusy(false)}}

  const carton=active?.carton;const items=active?.items||[];const isOpen=carton?.status==="OPEN";
  return <div className="manifestWorkspace">
    <section className="manifestHero"><div><span className="eyebrow">WAREHOUSE MANIFEST</span><h2>{carton?.carton_code||"Thùng mới sẽ được tạo khi nhập đơn"}</h2><p>Mỗi thùng gắn cố định Service / Sub-Service / Supplier và phân vùng nếu có. Mã thùng gồm Dịch vụ · Ngày · Số thứ tự xuất hàng trong ngày.</p></div><div className="manifestHeroStats"><div><span>Trạng thái</span><b className={isOpen?"open":"closed"}>{isOpen?"Đang đóng hàng":carton?.status==="PAUSED"?"Tạm dừng":carton?"Đã chốt":"Chưa mở"}</b></div><div><span>Full route</span><b>{carton?[carton.service,carton.sub_service,carton.supplier,carton.segment_key].filter(Boolean).join(" / "):"—"}</b></div><div><span>Orders</span><b>{Number(carton?.order_count||0)}</b></div><div><span>Kiện</span><b>{Number(carton?.item_count||0)}</b></div></div></section>
    <div className="manifestMainGrid"><section className="manifestPackingCard">
      <div className="manifestSteps"><div className="done"><i>1</i><span>Nhập đơn</span></div><div className={items.length?"done":""}><i>2</i><span>Kiểm tra kiện</span></div><div className={carton?.status==="CLOSED"?"done":""}><i>3</i><span>Đóng đầy thùng</span></div></div>
      <div className="manifestItemHead"><select aria-label="Scan mode" value={mode} disabled={busy} onChange={e=>setMode(e.target.value as "ADD"|"REMOVE")}><option value="ADD">Thêm vào thùng</option><option value="REMOVE">Bốc ra khỏi thùng</option></select><button disabled={busy} onClick={()=>{activeId.current=undefined;setActive(null);setMode("ADD")}}>Thùng mới</button>{carton&&<button disabled={busy} onClick={()=>void statusCarton(isOpen?"pause":carton.status==="PAUSED"?"resume":"reopen")}>{isOpen?"Tạm dừng":carton.status==="PAUSED"?"Tiếp tục":"Mở lại để chỉnh"}</button>}</div>
      <form className="manifestScanForm" onSubmit={(event:FormEvent)=>{event.preventDefault();void addIdentifiers(value)}}><label><span>Nhập DMD ID, Client Order ID hoặc Tracking</span><div><input ref={input} autoFocus value={value} disabled={busy||Boolean(carton&&!isOpen)} onChange={event=>setValue(event.target.value)} placeholder="Ví dụ DMD-20261004-000123 hoặc scan Tracking"/><button className="primaryBtn" disabled={busy||!value.trim()||Boolean(carton&&!isOpen)}>{mode==="ADD"?"Thêm vào thùng":"Bốc ra khỏi thùng"}</button></div></label></form>
      <details className="manifestPaste"><summary>Nhập nhiều đơn cùng lúc</summary><textarea value={paste} disabled={busy||Boolean(carton&&!isOpen)} onChange={event=>setPaste(event.target.value)} placeholder="Mỗi DMD ID / Client Order ID / Tracking một dòng"/><button className="secondaryBtn" disabled={busy||!paste.trim()} onClick={()=>void addIdentifiers(paste)}>Thêm danh sách</button></details>
      {notice&&<div className={notice.includes("Lỗi ·")?"manifestNotice error":"manifestNotice"} role="status">{notice.split("\n").map((line,index)=><p key={index}>{line}</p>)}</div>}
      <div className="manifestItemHead"><div><b>Kiện trong thùng</b><span>{items.length?`${items.length} kiện đã xác nhận`:"Chưa có kiện nào"}</span></div>{isOpen&&items.length>0&&<button className="closeCartonBtn" disabled={busy} onClick={()=>void closeCarton()}>✓ Chốt thùng</button>}{carton?.status==="CLOSED"&&<button className="primaryBtn" disabled={busy} onClick={()=>void exportCarton(carton)}>⇩ Xuất Manifest</button>}</div>
      <div className="manifestItems">{items.length?<table><thead><tr><th>STT</th><th>Order</th><th>Tracking</th><th>Khách / Người nhận</th><th>Carton</th><th></th></tr></thead><tbody>{items.map((item,index)=><tr key={item.item_id}><td><span className="manifestIndex">{index+1}</span></td><td><b>{item.system_order_code}</b><small>{item.client_order_id||"—"}</small></td><td><code>{item.tracking}</code><small>{[item.sub_service,item.supplier].filter(Boolean).join(" · ")}</small></td><td>{item.customer}<small>{item.recipient_name||"—"}</small></td><td>#{item.carton_number}</td><td>{isOpen&&<button className="removeManifestItem" disabled={busy} onClick={()=>void removeItem(item.item_id)}>Bỏ</button>}</td></tr>)}</tbody></table>:<div className="manifestEmpty"><div>▤</div><b>Quét đơn đầu tiên để mở thùng</b><span>Hệ thống kiểm tra Tracking, dịch vụ và tự cấp mã thùng.</span></div>}</div>
    {active?.history?.length ? <details><summary>Lịch sử thao tác</summary>{active.history.map(event=><p key={event.id}>{event.created_at} · {event.actor_name} · {event.action}</p>)}</details>:null}</section><aside className="manifestHistoryCard"><div className="manifestHistoryHead"><div><b>Các thùng gần đây</b><span>Chọn để xem hoặc xuất lại</span></div><button onClick={()=>void load()} disabled={busy}>↻</button></div><div className="manifestHistoryList">{cartons.length?cartons.map(row=><button key={row.id} className={row.id===carton?.id?"active":""} onClick={()=>void chooseCarton(row.id)}><div><b>{row.carton_code}</b><span>{[row.service,row.sub_service,row.supplier,row.segment_key].filter(Boolean).join(" / ")} · {displayDate(row.manifest_date)}</span></div><div><em className={row.status.toLowerCase()}>{row.status==="OPEN"?"Đang mở":row.status==="PAUSED"?"Tạm dừng":"Đã chốt"}</em><small>{row.item_count} kiện</small></div></button>):<div className="manifestHistoryEmpty">Chưa có thùng Manifest.</div>}</div></aside></div>
  </div>;
}
