"use client";
import {useCallback,useEffect,useState} from "react";
type Row=Record<string,unknown>;
type Field={name:string;label:string;type?:string;options?:string[];value?:string};
const statuses=['OPEN','INVESTIGATING','WAITING_CLIENT','WAITING_SUPPLIER','DECISION_PENDING'];
function ActionForm({title,url,action,fields,done}:{title:string;url:string;action:string;fields:Field[];done:()=>void}){
 const [busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const b:Row=Object.fromEntries(new FormData(e.currentTarget));if(b.order_ids)b.order_ids=String(b.order_ids).split(/[ ,\n]+/).filter(Boolean).map(Number);if(b.allocations){try{b.allocations=JSON.parse(String(b.allocations))}catch{setMessage('Allocation phải là JSON hợp lệ.');return;}}setBusy(true);try{const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...b,action})}),d=await r.json();if(!r.ok)throw Error(d.error);setMessage('Đã lưu'+(d.id||d.measurement_id?' #'+String(d.id||d.measurement_id):''));done();}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
 return <details className="panel"><summary>{title}</summary><form onSubmit={submit} className="settingsGrid">{fields.map(f=><label className="field" key={f.name}><span>{f.label}</span>{f.options?<select name={f.name} defaultValue={f.value}>{f.options.map(v=><option key={v}>{v}</option>)}</select>:<input name={f.name} type={f.type||'text'} step={f.type==='number'?'any':undefined} defaultValue={f.value} required={!['due_date','assigned_to','note','next_action'].includes(f.name)}/>}</label>)}<button className="primaryBtn" disabled={busy}>{busy?'Đang lưu…':'Lưu'}</button>{message&&<p role="status">{message}</p>}</form></details>;
}
const id=(name:string,label:string):Field=>({name,label,type:'number'}),amount=(name:string,label:string):Field=>({name,label,type:'number',value:'0'}),text=(name:string,label:string):Field=>({name,label}),date=(name:string,label:string):Field=>({name,label,type:'date'});
function Records({title,rows,columns}:{title:string;rows:Row[];columns:string[]}){return <section className="panel"><h3>{title} ({rows.length})</h3><div className="tableWrap"><table><thead><tr>{columns.map(k=><th key={k}>{({id:'ID',kind:'Loại',status:'Trạng thái',summary:'Nội dung',next_action:'Việc tiếp theo',due_date:'Deadline',assigned_to:'Người phụ trách',scan_key:'Mã nhận hàng',order_id:'Order',parcel_id:'Kiện inbound',amount_cents:'Số tiền USD',expected_cents:'Dự kiến USD',recovered_cents:'Thu hồi USD',case_id:'Claim',supplier:'Supplier',carton_id:'Carton',weight:'Kg',length:'Dài cm',width:'Rộng cm',height:'Cao cm',chargeable_weight:'Chargeable kg',month:'Tháng',matured_clients:'Khách ≥60 ngày',revenue:'Doanh thu USD',qualified_revenue:'Doanh thu đạt margin USD',revenue_share:'Tỷ trọng đạt margin',target_met:'Đạt target ≥20%'} as Row)[k] as string||k}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={String(r.id||r.month)}>{columns.map(k=><td key={k}>{k.endsWith('_cents')?'$'+(Number(r[k]||0)/100).toFixed(2):String(r[k]??'')}</td>)}</tr>)}</tbody></table></div></section>}
export function OperationsWorkspace({role}:{role:string}){
 const [cases,setCases]=useState<Row[]>([]),[inbound,setInbound]=useState<{parcels:Row[];adjustments:Row[];measurements:Row[]}>({parcels:[],adjustments:[],measurements:[]}),[recoveries,setRecoveries]=useState<Row[]>([]),[tower,setTower]=useState<Row|null>(null),[error,setError]=useState('');
 const load=useCallback(async()=>{try{const endpoints=['/api/cases','/api/control-tower',...(role!=='CLIENT'?['/api/inbound']:[]),...(role==='ADMIN'?['/api/claims']:[])];const all=await Promise.all(endpoints.map(async url=>{const r=await fetch(url),d=await r.json();if(!r.ok)throw Error(d.error);return d}));setCases(all[0].items);setTower(all[1]);if(role!=='CLIENT')setInbound(all[2]);if(role==='ADMIN')setRecoveries(all[3].items);setError('');}catch(e){setError((e as Error).message)}},[role]);
 useEffect(()=>{void load()},[load]);const done=()=>void load();const form=(title:string,url:string,action:string,fields:Field[])=><ActionForm key={action} title={title} url={url} action={action} fields={fields} done={done}/>;
 return <><section className="panel"><h2>Control Tower</h2><button onClick={done}>Làm mới</button>{error&&<p role="alert">{error}</p>}{tower&&<><p>Cập nhật {String(tower.as_of)}</p><div className="metricGrid">{Object.entries(tower.counts as Row).map(([k,v])=><div className="metricCard" key={k}><span>{({cancellation_approval:'Huỷ chờ duyệt',purchase_failed:'Mua thất bại',holds:'Đơn bị Hold',cases_due:'Case đến hạn',claims_overdue:'Claim quá SLA',weight_adjustments:'Phụ thu chờ duyệt',unidentified:'Hàng chưa định danh',accounts_overdue:'Client quá hạn',supplier_waiting:'Supplier chờ xử lý'} as Row)[k] as string}</span><b>{String(v)}</b></div>)}</div>{role==='ADMIN'&&<p>Đã chi claim: ${(Number(tower.client_claim_paid_cents)/100).toFixed(2)} · Supplier thu hồi: ${(Number(tower.supplier_recovered_cents)/100).toFixed(2)} · Claim loss: ${(Number(tower.net_claim_loss_cents)/100).toFixed(2)}</p>}{role==='ADMIN'&&<p>New Client Quality · rolling 30 ngày · sau 60 ngày · company margin {String((tower.new_client_quality as Row).company_margin_percent??"—")}% · target ≥20%: {(tower.new_client_quality as Row).revenue_share===null?'Chưa có doanh thu':(Number((tower.new_client_quality as Row).revenue_share)*100).toFixed(1)+'%'}</p>}{role!=='WAREHOUSE'&&<p>Balance: ${(Number((tower.money as Row).balance_cents)/100).toFixed(2)} · Đang giữ: ${(Number((tower.money as Row).reserved_cents)/100).toFixed(2)} · Công nợ còn lại: ${(Number((tower.money as Row).receivable_cents)/100).toFixed(2)}</p>}{role==='ADMIN'&&<Records title="Cohort theo tháng mua đầu tiên" rows={(tower.new_client_quality as Row).cohorts as Row[]} columns={['month','matured_clients','revenue','qualified_revenue','revenue_share','target_met']}/>}
 <details><summary>Danh sách việc đến hạn</summary>{Object.entries(tower.queues as Row).map(([k,v])=><p key={k}>{({cancellation_approval:"Huỷ chờ duyệt",purchase_failed:"Mua thất bại",holds:"Hold",cases_due:"Case đến hạn",claims_overdue:"Claim quá SLA",weight_adjustments:"Phụ thu",unidentified:"Hàng chưa định danh",accounts_overdue:"Client quá hạn",supplier_waiting:"Supplier chờ xử lý"} as Row)[k] as string}: {(v as Row[]).map(r=>String(r.id||r.order_id||r.client_id)).join(', ')||'—'}</p>)}</details></>}</section>
 {['ADMIN','SALES'].includes(role)&&form('Mua dịch vụ thay Client','/api/purchase-jobs','purchase',[id('order_id','Order ID')])}
 {form(role==='CLIENT'?'Mở Claim':'Mở Case / bulk Hold','/api/cases','create',[text('order_ids','Order ID (phân cách dấu phẩy)'),{name:'kind',label:'Loại',options:role==='CLIENT'?['CLAIM']:role==='WAREHOUSE'?['EXCEPTION','HOLD']:['EXCEPTION','HOLD','CLAIM']},{name:'visibility',label:'Hiển thị',options:role==='CLIENT'?['PUBLIC']:['INTERNAL','PUBLIC']},{name:'severity',label:'Mức độ',options:['MEDIUM','LOW','HIGH','CRITICAL']},text('summary','Nội dung'),text('next_action','Việc tiếp theo'),...(role!=='CLIENT'?[id('assigned_to','ID người phụ trách')]:[]),date('due_date','Deadline')])}
 <Records title="Cases & Claims" rows={cases} columns={['id','kind','status','summary','next_action','assigned_to','due_date']}/>
 {cases.map(c=><details className="panel" key={String(c.id)}><summary>Case #{String(c.id)} · lịch sử & phản hồi</summary><p>Orders: {(c.orders as Row[]).map(o=>String(o.order_id)).join(', ')}</p>{(c.events as Row[]).map(e=><p key={String(e.id)}>{String(e.created_at)} · {String(e.event)} · {(()=>{const d=JSON.parse(String(e.data_json));return String(d.message||d.summary||d.reason||d.status||'Đã cập nhật')})()}</p>)}</details>)}
 {form('Phản hồi case','/api/cases','comment',[id('case_id','Case ID'),text('message','Phản hồi'),{name:'visibility',label:'Hiển thị',options:role==='CLIENT'?['PUBLIC']:['INTERNAL','PUBLIC']}])}
 {role!=='CLIENT'&&form('Assignment / trạng thái / gỡ Hold','/api/cases','update',[id('case_id','Case ID'),{name:'status',label:'Trạng thái',options:[...statuses,...(role==='ADMIN'?['RESOLVED','CLOSED']:[])]},text('next_action','Việc tiếp theo'),id('assigned_to','ID người phụ trách'),date('due_date','Deadline')])}
 {['ADMIN','WAREHOUSE'].includes(role)&&form('Scan nhận hàng','/api/inbound','scan',[text('scan_key','Tracking / DMD ID / Client Order ID'),text('note','Ghi chú')])}
 {role!=='CLIENT'&&<><Records title="Inbound" rows={inbound.parcels} columns={['id','scan_key','order_id','status']}/><Records title="Kết quả cân đo" rows={inbound.measurements||[]} columns={['id','parcel_id','carton_id','weight','length','width','height','chargeable_weight']}/><Records title="Phụ thu cân đo" rows={inbound.adjustments} columns={['id','order_id','status','amount_cents']}/></>}
 {['ADMIN','SALES'].includes(role)&&form('Match hàng chưa định danh','/api/inbound','match',[id('parcel_id','Kiện inbound ID'),id('order_id','Order ID')])}
 {['ADMIN','WAREHOUSE'].includes(role)&&form('Cân đo carton','/api/inbound','measure',[id('parcel_id','Kiện inbound ID'),id('carton_id','Carton ID'),amount('weight','Cân nặng kg'),amount('length','Dài cm'),amount('width','Rộng cm'),amount('height','Cao cm')])}
 {['ADMIN','SALES'].includes(role)&&<>{form('Báo giá phụ thu route thủ công','/api/inbound','quote_adjustment',[id('parcel_id','Kiện inbound ID'),id('measurement_id','Measurement ID'),amount('amount','Phụ thu USD')])}{form('Duyệt phụ thu cân đo','/api/inbound','approve_adjustment',[id('parcel_id','Kiện inbound ID'),id('adjustment_id','Adjustment ID')])}{form('Từ chối phụ thu','/api/inbound','reject_adjustment',[id('parcel_id','Kiện inbound ID'),id('adjustment_id','Adjustment ID')])}</>}
 {role==='ADMIN'&&<>{form('Duyệt huỷ & hoàn tiền','/api/cancellation-requests','approve',[id('order_id','Order ID')])}{form('Đánh dấu mua thất bại','/api/purchase-jobs','fail',[id('order_id','Order ID'),text('reason','Lý do thất bại')])}{form('Retry mua đơn','/api/purchase-jobs','retry',[id('order_id','Order ID')])}{form('Finalize Claim','/api/claims','finalize',[id('case_id','Claim ID'),amount('refund_amount','Hoàn cước USD'),amount('compensation_amount','Bồi thường USD'),text('reason','Lý do quyết định')])}{form('Tạo Supplier Recovery','/api/claims','create_recovery',[id('case_id','Claim ID'),text('supplier','Supplier'),amount('expected_amount','Dự kiến thu hồi USD'),date('due_date','Deadline'),text('note','Ghi chú')])}<Records title="Supplier Recovery" rows={recoveries} columns={['id','case_id','supplier','status','expected_cents','recovered_cents','due_date']}/>{form('Cập nhật Supplier Recovery','/api/claims','recovery_status',[id('case_id','Claim ID'),id('recovery_id','Recovery ID'),{name:'status',label:'Trạng thái',options:['OPEN','SUBMITTED','WAITING_SUPPLIER','REJECTED','CLOSED']},date('due_date','Deadline'),text('note','Ghi chú')])}{form('Ghi nhận tiền thu hồi','/api/claims','receive_recovery',[id('case_id','Claim ID'),id('recovery_id','Recovery ID'),amount('amount','Thu hồi USD'),text('reference','Mã thanh toán'),date('occurred_at','Ngày nhận')])}</>}
 </>;
}
